name: dotnet-core-build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # dotnet: [ '2.2.x', '3.0.x', '3.1.x' ]
        dotnet: [ '3.1.202' ]
    name: dotnet core ${{ matrix.dotnet }}
    steps:
      - name: Get source
        uses: actions/checkout@v2
          # ref: ${github.ref##*/}

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Restore
        run: dotnet restore

      - name: Format
        run: |
          dotnet tool install -g dotnet-format
          dotnet format -v d -w fixeol.csproj

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --verbosity normal
